export const ACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",

  AUTH_SET: "AUTH_SET",
  AUTH_LOGOUT: "AUTH_LOGOUT",

  EMPLOYEES_SET: "EMPLOYEES_SET",
  EMPLOYEE_ADD: "EMPLOYEE_ADD",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  EMPLOYEE_REMOVE: "EMPLOYEE_REMOVE",
  SALARIES_SET: "SALARIES_SET",
  SALARY_ADD: "SALARY_ADD",
  PROMOTIONS_SET: "PROMOTIONS_SET",
  PROMOTION_ADD: "PROMOTION_ADD",
  CREDENTIAL_SET: "CREDENTIAL_SET",
  CREDENTIAL_ADD: "CREDENTIAL_ADD",
  EMPLOYMENTS_SET: "EMPLOYMENTS_SET",
  EMPLOYMENT_ADD: "EMPLOYMENT_ADD",
  LEAVE_CREDITS_SET: "LEAVE_CREDITS_SET",
  LEAVE_CREDIT_UPSERT: "LEAVE_CREDIT_UPSERT",
  LEAVE_REQUESTS_SET: "LEAVE_REQUESTS_SET",
  LEAVE_REQUEST_ADD: "LEAVE_REQUEST_ADD",
  LEAVE_REQUEST_UPDATE: "LEAVE_REQUEST_UPDATE",







};
